version: "3.9"
services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: rfp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rfp
      POSTGRES_USER: rfp_user
      POSTGRES_PASSWORD: rfp_pass
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rfp_user -d rfp"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
      - postgres-log:/var/lib/docker/container/<container-id>

  
  mongodb-atlas:
    image: mongodb/mongodb-atlas-local:latest
    container_name: rfp_atlas
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_ROOT_PASSWORD: admin123
      MONGODB_INITDB_DATABASE: chat_store
    healthcheck:
      test: ["CMD", "mongosh", "mongodb://admin:admin123@localhost:27017/?authSource=admin", "--eval", "db.adminCommand('ping')"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always
    volumes:
      - mongo_data:/data/db
      - config:/data/configdb
      - ./init-scripts:/docker-enttrypoint-initdb.d:ro
    

  redis:
    image: redis:7-alpine
    container_name: rfp_redis
    ports:
      - "6379:6379"

  minio:
    image: quay.io/minio/minio
    container_name: rfp_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minio4321
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    container_name: rfp_api
    depends_on:
      - postgres
      - redis
      - minio
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://rfp_user:rfp_pass@postgres:5432/rfp?schema=public
      REDIS_URL: redis://redis:6379
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_BUCKET: rfp-bucket
      JWT_SECRET: dev_secret_change_me
      OPENAI_API_KEY: ""
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    networks:
      - backend
    working_dir: /app/services/api
    command: sh -c "cd /app && npm install && cd services/api && npx prisma migrate deploy || npx prisma migrate dev --name init && npm run dev"

  worker:
    build:
      context: .
      dockerfile: services/worker/Dockerfile
    container_name: rfp_worker
    depends_on:
      - redis
      - api
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      OPENAI_API_KEY: ""
    volumes:
      - ./:/app
    working_dir: /app/services/worker
    networks:
      - backend
    command: sh -c "cd /app && npm install && cd services/worker && npm run dev"

volumes:
  pgdata:
  minio_data:
  postgres-log:
  mongo_data:
  config:
  init-scripts:

networks:
  backend:
